server:
  port: 8091
spring:
  datasource:
    username: hot_pot_shop
    password: 9115f53f38
    url: jdbc:mysql://1.15.137.216:3306/hot_pot_shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:/mapper/*.xml
alioss:
  endPoint: oss-cn-shenzhen.aliyuncs.com
  bucketName: decoration01
  keyId: LTAI4G2q6gv7dC7LP8jvZpd7
  keySecret: IOPQCZkFPYKp1Yjwcn1bQoOHXEGYeb
logging:
  level.com.runnersoftware.hot_pot_shop: debug
